### ISSUE TITLE
Add word cloud / add more simple words to filter

### ISSUE THREAD

**Issue by mfmarlow** [BryceStevenWilley/visioning_texts#10]
- I think another cool visualization you could add here is a word cloud for each person.

- Add more "simple" words to the filter. I noticed a lot of simple words in the "Word Use Difference" section. Mostly contractions (isn't, aren't, he's, she's, it's,...)

**Comment by BryceStevenWilley** [comment]
I'm honestly not a huge fan of word clouds, just IMO.  I tried to get the same idea conveyed with the word difference chart, but losing frequency makes it a lot more difficult to grasp I think.  There's probably some way to do it better, I'll think about it.

And certainly, I should add some more simple words. I wanted to keep it a "simple" list, but there's probably some industry standard of filler words to drop, I'll take a look. Thanks!
