### ISSUE TITLE
Support for Facebook Messenger

### ISSUE THREAD

**Issue by oisinq** [BryceStevenWilley/visioning_texts#11]
Similar to #1, but I thought I'd make a request for Messenger individually because it's not exactly part of the original issue. Facebook let's you export your entire message history 

I think I'd be happy to help out with this myself in the future when I've actually got some spare time

**Comment by BryceStevenWilley** [comment]
I wouldn't mind doing this, I did find https://ericezam.github.io/MessengerDataAnalysis/ in the reddit comments though. I haven't tried it, but it honestly fills most of the same features (offline/local, your data, open source).  I wouldn't refuse a PR implementing though! ;)  Feel free to ask any question about code structure, I wasn't expected that much attention this quickly, it's not well documented at the moment.

**Comment by HexaCubist** [comment]
See PR #17 for a semi-tested implementation of this.

**Comment by BryceStevenWilley** [comment]
With #17 merged, this is already in! Open source is amazing.
