### ISSUE TITLE
Signal CSV to upload

### ISSUE THREAD

**Issue by ellieboydarttt** [BryceStevenWilley/visioning_texts#15]
Hello there, 

I found you post of r/dataisbeautiful and I have been trying all night to upload the text conversation with my boyfriend and I to your code. It seems very interesting. Thank you for going through the time to build the program. Although I am running into a problem when I try to upload a csv file to the site. When I download the windows_amd64 it automatically wants to format the signal.backup to a xml. So I re-worded the code with the line of code on your help page, except with the windows format of course. That worked and it did make a .csv file in the local folder. Although when I go to upload that file it fails. I'm wondering if you've come across this problem in testing and maybe have a solution. 

Thanks so much, 

Ellie

**Comment by BryceStevenWilley** [comment]
Hey Ellie,

What's error say when the upload fails?  I added a bit that says what file type it is when the upload fails.
What ever's in the console log (F12 in chrome, go to the "console" tab) would also help!

**Comment by ellieboydarttt** [comment]
Also when I press f12 and go to the console tab it appears to be empty.

**Comment by ellieboydarttt** [comment]
Hi Bryce,

Thanks for responding. The error says "Can't read this type of file () at
the moment.Please try a Signal csv, or a WhatsApp text file" .

and the Console tab when I press f12 is empty.
Ellie

**Comment by BryceStevenWilley** [comment]
Strange, in that case it doesn't seem to be finding a file type at all. The file you are uploading does have an extension, right?

**Comment by ellieboydarttt** [comment]
Yup it's a .csv file although it doesn't seem to have an data in it. The
converter for GitHub has no problem converting the messages into an xml
program but I can't seem to find any command for Windows to convert the
messages to csv. I'll keep testing to see if i can figure it out.

**Comment by BryceStevenWilley** [comment]
I'll also take a look at the process for Windows this evening, and let you know if I come across any similar problems.

**Comment by dwbnerd** [comment]
I just tried to upload a random document on windows and it isn't getting the extension on it either for the denial.

**Comment by BryceStevenWilley** [comment]
Hey @ellieboydarttt, @dwbnerd,  with https://github.com/BryceStevenWilley/visioning_texts/commit/3c620379fc1bdbd9a19f310bf2b3a951328cbf7e I've changed the website to not assume that there will be a type associated with the file given. Give it another shot and let me know if it's working.

**Comment by BryceStevenWilley** [comment]
This should be fixed. Let me know if you're still running into issues!
