### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Tuteav** [BryceStevenWilley/visioning_texts#18]
Im getting the folowing error when trying to get my data from my 3 years old conversation with my GF: 

> graphs.js:73 Uncaught RangeError: Maximum call stack size exceeded
>     at set_graph_0_whisk (graphs.js:73)
>     at set_graph_0 (graphs.js:149)
>     at FileReader.<anonymous> (graphs.js:490)
> set_graph_0_whisk @ graphs.js:73
> set_graph_0 @ graphs.js:149
> (anonymous) @ graphs.js:490
> load (async)
> trigger_process @ graphs.js:476
> onclick @ (index):57

The chat has over 160000 messages so that might be a problem. Tried the program on a 10k messages chat with the same properties (Emoji on the contact name, same datee and time format, etc) and it worked

**Comment by BryceStevenWilley** [comment]
That's interesting. I guess JS just straight up puts the whole array on the stack. I'll try to fix that this week, will ping here when I think it's fixed. Thanks for the report!

**Comment by htkcodes** [comment]
#23

**Comment by BryceStevenWilley** [comment]
Thanks to htcodes, this has been fixed! @Tuteav, feel free to give this another try!

**Comment by Tuteav** [comment]
Yes, It has been fixed ! I have other issues now lol but gonna report them on another issues.
