### ISSUE TITLE
Emojis and Word Counts

### ISSUE THREAD

**Issue by DrNicky** [BryceStevenWilley/visioning_texts#22]
I have imported a 3 year WhatsApp convo into your visioning. But as the difference in word counts per message and the usage of Emojis differs to much it doesn't visualize it in any way that I can see it completly. The other thing is that it doesn't show the word usage of the users at all.
Apart from that an awesome tool already

**Comment by htkcodes** [comment]
Could be the size of the conversation. It will be resolved soon, i presume

**Comment by BryceStevenWilley** [comment]
As htkcodes has mentioned, the size issues should be resolved now. @DrNicky, take another look to see if there are still issues. If there are, could you give some more information about what's going wrong?
* console log (F12, console tab)
* a screen shot if something is wrong visually

**Comment by BryceStevenWilley** [comment]
Gonna close this, feel free to reopen if you're still having issues.
