### ISSUE TITLE
[BUG] Everything is broken with whatsapp chat log

### ISSUE THREAD

**Issue by lukeeexd** [BryceStevenWilley/visioning_texts#24]
**Describe the bug**

Nothing displays after uploading whatsapp chat log

**Expected behavior**
Everything not to be fucked

**Screenshots**
https://i.tws.gg/oTBJQJnVg3.png

**Desktop (please complete the following information):**
 - OS: Windows[e.g. iOS]
 - Browser: Chrome [e.g. chrome, safari]
 - Version: Latest [e.g. 22]

**Additional context**
If it's a text format, what does a typical line of your message file look like? (If it's CSV, please include the first line as well).

**Comment by BryceStevenWilley** [comment]
What's a typical line in your chat log look like?

**Comment by lukeeexd** [comment]
The contact has an emoji in their name so it comes out all funny in the log. Maybe thats why?

**Comment by BryceStevenWilley** [comment]
Shouldn't be the case, I've been testing with a contact with an emoji in their name as well.  This is likely a date parsing issue, i.e. the first part of each line isn't what the site expects.  Can you show what that looks like for you?

**Comment by lukeeexd** [comment]
[31/12/2019, 2:14:40 a.m.]

**Comment by BryceStevenWilley** [comment]
Ohh, I haven't seen `a.m.` yet, just `AM`. Adding that to the test suite, thanks!

**Comment by lukeeexd** [comment]
pm is the same `p.m.`

**Comment by lukeeexd** [comment]
Just tested it by replacing the a.m. and p.m. with AM and PM and it works. Except this https://i.tws.gg/hDlIAPQArT.png lol

**Comment by BryceStevenWilley** [comment]
@lukeeexd, you should be able to have things work without manually changing the data now. The too-large emoji's are still an issue though, being tracked in #27.

**Comment by BryceStevenWilley** [comment]
The `a.m./p.m.` parsing should be okay now. Feel free to reopen if you still have issues.
