### ISSUE TITLE
Stuck on Message Statistics

### ISSUE THREAD

**Issue by greychives** [BryceStevenWilley/visioning_texts#25]
Does not show any more stats
![image](https://user-images.githubusercontent.com/60154357/72835716-25284580-3c83-11ea-8ec4-e64dc3fa90c4.png)

Chrome console gives the following:
![image](https://user-images.githubusercontent.com/60154357/72835768-3a04d900-3c83-11ea-8695-d14c4b8d600a.png)

Are there too many messages for it to handle?

**Comment by htkcodes** [comment]
Yes, it should be fixed soon, waiting on a merge. see #23

**Comment by BryceStevenWilley** [comment]
@greychives The fix should be in thanks to @htkcodes, try again when you get the chance.

**Comment by greychives** [comment]
Hiya,

Thanks for the speedy response!

Thanks again!
