### ISSUE TITLE
[BUG]signal csv not recognised

### ISSUE THREAD

**Issue by dwbnerd** [BryceStevenWilley/visioning_texts#26]
**Describe the bug**
I have followed the instructions for windows from your website (amd_64 converter) I got a Backup.csv file that when opened contains data. I attempt to upload it to the website and it says, "Can't read this type of file () at the moment. Please try a Signal csv, or a WhatsApp text file"
![Capture](https://user-images.githubusercontent.com/60155415/72838545-56822080-3c45-11ea-938d-4abd18c2a45c.PNG)

**Comment by BryceStevenWilley** [comment]
This is a dup of #15.  I'm going to go through the windows process and see what exactly is happening, because it doesn't make a lot of sense that there is no file type.

**Comment by BryceStevenWilley** [comment]
@dwbnerd I added made the uploader a little more forgiving, it should still try to load things without types, as long as the extension is correct. Let me know if it works for you!

**Comment by dwbnerd** [comment]
That seems to have fixed this thing is really awesome!
