### ISSUE TITLE
WHATSAPP: It doesnt load the visualisation

### ISSUE THREAD

**Issue by nexo4life** [BryceStevenWilley/visioning_texts#32]
so 2 questions
1) I can only upload the chat file,however in your example you had statistics about media files sent. It doesnt let me upload any media files tho so how do I fix this?

2) When I upload my chat file it and press 'show data' litteraly nothing happens, I dont know what to do.

I downloaded the whatsapp data from my iphone ( tried US and EU but they end up being the same file(?)), and it used my pc (windows) to import the date on the site.

Thank you in advance
Nexo

**Comment by biejay** [comment]
`When I upload my chat file it and press 'show data' litteraly nothing happens, I dont know what to do.`

Can you **track** the **CPU Usage** of Chrome or whatever Browser you are using? When you are uploading huge files (several MBs) it takes some time until something happens. My CPU usage increases to ~10-20% for the chrome process when i hit "show data".

**Comment by nexo4life** [comment]
Okay so now it doest work on Chrome, however, im still unsure how you can add the media files-data in there, it only lets me add the chat file.

**Comment by BryceStevenWilley** [comment]
Hey @nexo4life, there must be some misunderstanding, the app has never supported media files. Your Whatsapp text export might include that media messages were sent, but the app doesn't track what kind of media, or any image information yet.

**Comment by BryceStevenWilley** [comment]
Closing, feel free to reopen if it's chat/text isn't fixed for you.
