### ISSUE TITLE
Locally Downloaded Website Does Not Allow Uploading of a File

### ISSUE THREAD

**Issue by towfiqueA** [BryceStevenWilley/visioning_texts#38]
Downloading all the code and running locally doesn't work, whereas using the live website _does_ work.

The specific issue seen with the local website is after clicking on "Choose your Messages File" and selecting a text file, nothing occurs. Whereas, on the live website, it will show the filename with file information, and a button to "Show data".

I've tried this on Windows 7 and Windows 10, using both Chrome and Firefox browsers.

**Comment by BryceStevenWilley** [comment]
Good catch, I think I shouldn't have changed the javascript files to modules in [last commit](https://github.com/BryceStevenWilley/visioning_texts/commit/d1485d284c771d42bc929cf5e06bd9bfeaf0fee6), as [modules don't load from local js files](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts) for security reasons. I'll try to patch this soon, but until then you can checkout the previous commit (after running `git clone ...`, run `git checkout 98fc0da4cfb68e6b0a3f0c5072fdc1b41924fd5c`), and things should work again.
