### ISSUE TITLE
Unable to read CSV from Signal backup

### ISSUE THREAD

**Issue by zaynesember** [BryceStevenWilley/visioning_texts#4]
Followed your instructions for Windows and upon feeding it the CSV I got this error dialog (running locally not on your site):
![image](https://user-images.githubusercontent.com/25585887/72746645-9a5f2200-3b80-11ea-9d3e-a7edccb9b992.png)

**Comment by BryceStevenWilley** [comment]
Weird, it should only reading the file extension to  throw that error window.  Are you uploading the CSV itself, or are you uploading the signal backup file?

**Comment by zaynesember** [comment]
> Weird, it should only reading the file extension to throw that error window. Are you uploading the CSV itself, or are you uploading the signal backup file?

I'm uploading the CSV made from the tool you recommend on your site, maybe it's some sort of issue with the CSV encoding?

**Comment by BryceStevenWilley** [comment]
Likely is, yeah. I'm currently just getting the type from JS's FileReader (https://developer.mozilla.org/en-US/docs/Web/API/Blob/type).  I'll come up with a better check, might ask you to try to upload again to get some better debugging info.

**Comment by zaynesember** [comment]
Alright cool, just lmk.

**Comment by Zleox** [comment]
When uploading a CSV file from Windows, the MIME type is set as 'application/vnd.ms-excel'. The app is only expecting 'text/plain' or 'text/csv'.

**Comment by zaynesember** [comment]
So I tried to get around this by copying the text of the csv on my Windows machine and then making the actual CSV on Linux but I'm still getting the same error

**Comment by BryceStevenWilley** [comment]
@Zleox that's a great insight, thanks for that info. I had no clue that MIME types would differ from OS to OS. And unfortunate, @zaynesember.  I'll ping you when I have the new debug output in.

**Comment by BryceStevenWilley** [comment]
@zaynesember I pushed the fix that Zleox mentioned, and also should provide the type of file that the browser is reading your data as.  Let me know what it is when you get a chance.

**Comment by BryceStevenWilley** [comment]
This should be fixed, gonna close.
