### ISSUE TITLE
Extra Participants pt 2

### ISSUE THREAD

**Issue by ykilm** [BryceStevenWilley/visioning_texts#6]
I downloaded my WhatsApp export and emailed it to myself. I then downloaded the zip from the email and unzipped it. Then selected that unzipped txt file as the one to use on the site.  Heres what showed up:
![Captyftfgyhcrture](https://user-images.githubusercontent.com/57972270/72752851-29b40780-3b78-11ea-930d-29e06e1c971a.JPG) 
Any advice?

**Comment by ykilm** [comment]
Also heres the console log:
```
Uncaught TypeError: Cannot read property 'texts' of undefined
    at math.js:100
    at Array.reduce (<anonymous>)
    at xy_time_of_day (math.js:99)
    at graphs.js:485
```

**Comment by BryceStevenWilley** [comment]
I think this is related to #2, which I believe I made some progress on. @ykilm, try again, please let me know if anything is better!

**Comment by ykilm** [comment]
I tried it again and now there's no weird circle of characters but now there's nothing.

```
Uncaught TypeError: Cannot read property 'map' of undefined
    at total_to_from_data (math.js:95)
    at set_graph_0 (graphs.js:137)
    at FileReader.<anonymous> (graphs.js:483)
```

**Comment by ykilm** [comment]
Wait no now its back

**Comment by BryceStevenWilley** [comment]
Hey @ykilm, I've made some progress on this, It was likely something wrong with the date formatting. Can you check if it's working for you again, and if not, could you provide a typical date format from your file?

**Comment by ykilm** [comment]
It seems to be mostly working now. The average word/character per text still isn't working tho.
![Imjlhage 2](https://user-images.githubusercontent.com/57972270/72865824-109d7a80-3c8e-11ea-9cfa-f941c3433454.png)

There isn't anything in the console.

**Comment by BryceStevenWilley** [comment]
I gotcha.  That average word/char bug just the fact that I need a better way to handle extreme outliers, which is being tracked in #8.  Closing this, as it's fixed.
