### ISSUE TITLE
Whisker plots too narrow with high outlier

### ISSUE THREAD

**Issue by maartenwiegers** [BryceStevenWilley/visioning_texts#8]
The whisker plot seems to be too narrow when the high outlier is way higher than Q1-median-Q4:

![image](https://user-images.githubusercontent.com/60118494/72763456-29515600-3be4-11ea-87c0-286194da6e0e.png)
Considering that 2 other graphs are significantly wider, the solution might already be in making them wider?

**Comment by mfmarlow** [comment]
I had the same issue

**Comment by BryceStevenWilley** [comment]
Just pushed a commit that might help. It's hard to scale this one relative to the other graphs, as it could just be as big as necessary, but necessary meaning "make sure the user can read the full whisker plot" is pretty difficult to calculate on the fly. Let me know if it works better, if not I can try something more fancy.

**Comment by maartenwiegers** [comment]
Thanks! On the current version, it looks like this: 
![image](https://user-images.githubusercontent.com/60118494/72878098-9d7e1d80-3cfa-11ea-8f50-dcc886b00552.png)
So it does work a little better, but the bottom one is still not quite useful.

**Comment by BryceStevenWilley** [comment]
Thanks Maarten. I think I have an potential solution to this, will try to add it in the next few days.

**Comment by BryceStevenWilley** [comment]
Just pushed another fix, this time it adds a zoomed-in version of just the box, still labeled, and leaves out the label on the top. Let me know what y'all think!

**Comment by BryceStevenWilley** [comment]
Gonna close this, it should automatically "zoom" into the whisker plot for you now. Feel free to reopen if it's not working/ is wonky.
